axiomhq/axiom-py

pyproject.toml

The library also works without a problem with Python 3.8, so I think we should include it in the supported Python versions

Update pyproject.toml to support Python 3.8

---

axiom/datasets.py
axiom/logging.py

enforce log level for urllib3 to `WARNING`, so that it doesn't flood the logs
with debuging messages.

set urllib3 log level to warning

---

tests/test_datasets.py

You can't override the timestamp-field and have the default (`_time`)
still present in your data.

Fix typos, incompatible time fields

---

README.md
axiom/datasets.py
axiom/query/query.py
axiom/query/result.py
tests/test_datasets.py

- The query function now does an APL query, if you want to keep using the non-apl query function, you can use queryLegacy. 
queryLegacy will go away in the future.

promote apl query over query_legacy

---

README.md

DX-432 Use shields.io badges instead of GitHub badges

---

README.md

The datatime,timedelta and rfc3339 imports were missing from the readme example
And the os module is not needed

Add missing imports in readme example

---

axiom/client.py

this serializer is applied to the ujson calls but not to the tracing ingestion calls

fix: use a default serializer in ndjson

---

axiom/logging.py

`time.time()` can change suddenly (and go backwards) since it reflects the system date/time. A monotonic source avoids this class of problem.

bugfix: use `time.monotonic()` when calculating intervals

---

axiom/client.py
pyproject.toml
tests/test_client.py

This also removes the `no_cache` and `save` flags as they are undocumented.
This also bumps the version to 0.5.0 (breaking change).

feat: Add cursor, includeCursor options, bump version

---

axiom/client.py
axiom/query/result.py
tests/test_annotations.py
tests/test_datasets.py

This PR replaces all uses of `Any` with `object`.
The _correct_ (but obscure) annotation to express "could be anything" is `object`, which will encourage callers to check narrow the type first. Using `Any` disables all type checkers instead.
I stumbled over this when I naively wrote `result.data["tag"].lower()`.

feat(typing): Prefer `object` over `Any`

---

.github/workflows/ci.yml
axiom/__init__.py
axiom/annotations.py
axiom/client.py
axiom/datasets.py
axiom/query/__init__.py
axiom/query/query.py
axiom/query/result.py
axiom/version.py
examples/delete_dataset.py
examples/ingest.py
pyproject.toml
tests/test_annotations.py
tests/test_client.py

This also moves the version into `version.py` to prevent circular imports.

feat: Replace black + pylint w/ ruff

---

.github/workflows/ci.yml
.pre-commit-config.yaml
.pylintrc
README.md
pyproject.toml
shell.nix
tests/test_annotations.py
tests/test_client.py
tests/test_datasets.py

* Add pre-commit, configure for (local) ruff
* Add Python 3.12 to test matrix
* Remove (outdated) shell.nix
* Remove .pylintrc, we're using ruff now
* Reduce line lengths in some tests

Even more spring cleaning

---

src/axiom_py/client.py
tests/test_client.py

Fixes #76 by adding support for `atexit` shutdown hooks by default.
The shutdown hook can be called explicitly for more complex ( threaded ) applications

Add client atexit shutdown hook on process exit

---

pyproject.toml

Fixes #127 missing iso8601 dependency discovered by @glarec and confirmed with `deptry` tool

Fix missing dependency on iso8601 in pyproject.toml

---

README.md
examples/client.py
src/axiom_py/users.py

This also reverts 3ee7584 as API tokens won't work with e.g. /v2/user

Upgrade users.current to v2

---

src/axiom_py/client.py
src/axiom_py/query/__init__.py
src/axiom_py/query/result.py
src/axiom_py/util.py
tests/test_client.py

* Replace `MessageCode` w/ `str` as we have no way of knowing future message codes
* Adds support for the tabular format
* Adds iterator support to each table for better ergonomics

feat: Add support for tabular format

---

pyproject.toml
src/axiom_py/__init__.py
src/axiom_py/client.py
src/axiom_py/version.py
tests/test_client.py
tests/test_datasets.py
uv.lock

This adds the AxiomError exception, parsing the Axiom error response. If the response does not match the JSON format, it falls back to a generic HTTP error.

feat: Add AxiomError for more detailed error messages

---

src/axiom_py/annotations.py
src/axiom_py/client.py
src/axiom_py/datasets.py
src/axiom_py/logging.py
tests/test_logger.py

- Remove log statements from library

fix: Add a threading.Timer to ensure logs are flushed

---

tests/test_client.py

This tries to reproduce https://github.com/axiomhq/axiom-py/issues/151.

test: Add test with query status messages

---

src/axiom_py/client.py

This adds support for setting the `limit` in the `AplOptions` object so that the query limit can be specified as part of the request.

Add limit to `client.AplOptions`

---

.github/workflows/ci.yml
README.md
src/axiom_py/query/__init__.py
src/axiom_py/query/aggregation.py
src/axiom_py/util.py
tests/test_client.py

As the request is included in the response, we fail to decode if any aggregations are added after the fact.

fix: Remove aggregation enum

---

src/axiom_py/query/aggregation.py

This fixes the following error:
dacite.exceptions.WrongTypeError: wrong value type for field
"request.aggregations.argument" - should be "any" instead of value "15" of type "int"

fix: Use typings.Any instead of any
